### ISSUE TITLE
UI - update styling for accordion 

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/docs#156]
#### Issue

Currently accordion hides the actual content that must be visible upfront

#### Potential approach 

Find some UI / UX to show below details upfront on the page instead hidden behind accordion

![image](https://user-images.githubusercontent.com/12962843/186574763-91aa04ac-5049-4cf1-9695-5045a441c76d.png)

**Comment by devyani-kaushik** [comment]
- [ ] need to fix padding below title https://docs.open-metadata.org/openmetadata/connectors/database/athena
<img width="863" alt="Screenshot 2022-08-27 at 12 46 55 PM" src="https://user-images.githubusercontent.com/103238069/187019614-bc639e14-9e2a-41eb-8b10-d564ea8f4165.png">

- [ ] need better images https://docs.open-metadata.org/openmetadata/connectors/database/bigquery
<img width="592" alt="Screenshot 2022-08-27 at 12 49 51 PM" src="https://user-images.githubusercontent.com/103238069/187019711-62f56731-9108-4b5b-8472-f0b9a199107f.png">

fix spacing
<img width="857" alt="Screenshot 2022-08-27 at 12 52 10 PM" src="https://user-images.githubusercontent.com/103238069/187019794-7ab760e4-e1f9-4100-9b99-54538cd5dc48.png">

**Comment by devyani-kaushik** [comment]
Pages that seem to be missing data
https://docs.open-metadata.org/developers/webhooks
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/api
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/api/data
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/entity
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/entity/events
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/entity/feed
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/entity/policies
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/entity/services
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/entity/teams
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/metadataingestion
https://docs.open-metadata.org/main-concepts/metadata-standard/schemas/security

**Comment by pmbrull** [comment]
Thanks @devyani-kaushik. Fixed some of the above. The links from the `metadata-standard` are automatically generated as a way to check the JSON Schemas directly from the docs. We can improve this later
