### ISSUE TITLE
Still have questions?

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/docs#25]
update the component 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/35870520/175887571-fd89dad5-d255-49e5-aac0-e38389f2c330.png">

to point to our github discussions and slack #support channel

**Comment by harsh-vador** [comment]
<img width="620" alt="Screenshot 2022-06-29 at 5 09 40 PM" src="https://user-images.githubusercontent.com/58542468/176427978-39a99c0e-4978-4f5b-befc-51d08d1900b1.png">
