### ISSUE TITLE
Was this page helpful?

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/docs#27]
Review where this data is being sent and if it makes sense for us to integrate it somewhere else.

If we need to do this later on, for now we could just disable the component

**Comment by pmbrull** [comment]
this style of feedback is cool IMO 
<img width="687" alt="image" src="https://user-images.githubusercontent.com/35870520/175890265-96f091b3-05cd-47d3-a097-eb9b576827c6.png">
 just leaving it as a reference

**Comment by harsh-vador** [comment]
> this style of feedback is cool IMO <img alt="image" width="687" src="https://user-images.githubusercontent.com/35870520/175890265-96f091b3-05cd-47d3-a097-eb9b576827c6.png"> just leaving it as a reference

This looks good
